import { courseFiles, questionHtml } from "../courseFiles";
import { VersionRange } from "../plVersion";
import { BaseName } from "./bases";

/**
 * Every place a course file names another file that must exist. Each spec
 * drives, from this one table:
 *   - an existence rule (`rule`, registered in rules/registry.ts),
 *   - editor jump-to-file, and
 *   - "uses" (the reverse index in ../referenceIndex.ts).
 *
 * Deliberately not listed:
 *   - nodeModules* / core* dependencies: files on the PrairieLearn server.
 *   - workspaceOptions.gradedFiles, and `file-name` on pl-image-capture,
 *     pl-file-editor, pl-file-upload, pl-rich-text-editor: student submissions.
 *   - type="dynamic" pl-figure / pl-file-download: generated by server.py.
 */

/** Matches a property key or array index; "*" matches any key or index. */
export type PathSegment = string | RegExp;

/**
 * How an element's `directory` attribute picks the base directory.
 * `named` maps attribute values to bases; with `relative`, any other value
 * is a path relative to the question directory.
 */
interface DirectoryAttr {
  default: string;
  named: Readonly<Record<string, BaseName>>;
  relative?: true;
}

interface JsonSource {
  json: readonly PathSegment[];
  base: BaseName;
}

interface HtmlSource {
  tag: string;
  attr: string;
  /** Without one, values are relative to `base`. */
  directory?: DirectoryAttr;
  base?: BaseName;
  /** Skip elements with type="dynamic" (generated files). */
  staticOnly?: true;
}

/**
 * What must exist: a file, a directory, either, or a question (a directory
 * under questions/ with info.json and, usually, question.html).
 */
export type TargetKind = "file" | "fileOrDir" | "question";

interface BaseSpec<Rule extends string> {
  /** Stable id, used in tests and for debugging. */
  id: string;
  range: VersionRange;
  /** Glob, relative to the course root, of files holding the reference. */
  files: string;
  rule: Rule;
  target: TargetKind;
  /** Severity of a missing target; defaults to error. */
  severity?: "warning";
}

export type RefSpec<Rule extends string = string> = BaseSpec<Rule> &
  ({ source: "json"; json: JsonSource } | { source: "html"; html: HtmlSource });

const json = (path: readonly PathSegment[], base: BaseName) =>
  ({ source: "json", json: { json: path, base } }) as const;

const html = (source: HtmlSource) => ({ source: "html", html: source }) as const;

const clientFilesCourseDeps = /^clientFilesCourse(Styles|Scripts)$/;
const elementFiles = [courseFiles.element, courseFiles.elementExtension] as const;

/** pl-code, pl-file-editor, pl-graph, pl-rich-text-editor. */
const sourceFileDirectory: DirectoryAttr = {
  default: ".",
  named: { serverFilesCourse: "serverFilesCourse", clientFilesCourse: "clientFilesCourse" },
  relative: true,
};

const clientFilesDirectory: DirectoryAttr = {
  default: "clientFilesQuestion",
  named: { clientFilesQuestion: "clientFilesQuestion", clientFilesCourse: "clientFilesCourse" },
};

export const refSpecs = [
  // ── Question info.json ──
  {
    id: "question.dependencies.clientFilesCourse",
    range: "*", files: courseFiles.question, rule: "client-files-course-exist", target: "file",
    ...json(["dependencies", clientFilesCourseDeps, "*"], "clientFilesCourse"),
  },
  {
    id: "question.dependencies.clientFilesQuestion",
    range: "*", files: courseFiles.question, rule: "client-files-question-exist", target: "file",
    ...json(["dependencies", /^clientFilesQuestion(Styles|Scripts)$/, "*"], "clientFilesQuestion"),
  },
  {
    id: "question.clientFiles",
    range: "*", files: courseFiles.question, rule: "client-files-question-exist", target: "file",
    severity: "warning", // deprecated, and only served on request
    ...json(["clientFiles", "*"], "fileDir"),
  },
  {
    id: "question.externalGradingOptions.serverFilesCourse",
    range: "*", files: courseFiles.question, rule: "server-files-course-exist", target: "fileOrDir",
    ...json(["externalGradingOptions", "serverFilesCourse", "*"], "serverFilesCourse"),
  },
  {
    id: "question.template",
    range: "*", files: courseFiles.question, rule: "question-exists", target: "question",
    ...json(["template"], "questions"),
  },

  // ── Course elements and element extensions ──
  ...elementFiles.flatMap((files) => [
    {
      id: `${files}.controller`,
      range: "*", files, rule: "element-files-exist", target: "file",
      ...json(["controller"], "fileDir"),
    },
    {
      id: `${files}.dependencies.element`,
      range: "*", files, rule: "element-files-exist", target: "file",
      ...json(["dependencies", /^(element|extension)(Styles|Scripts)$/, "*"], "fileDir"),
    },
    {
      id: `${files}.dynamicDependencies.element`,
      range: "*", files, rule: "element-files-exist", target: "file",
      ...json(["dynamicDependencies", /^(element|extension)Scripts$/, "*"], "fileDir"),
    },
    {
      id: `${files}.dependencies.clientFilesCourse`,
      range: "*", files, rule: "client-files-course-exist", target: "file",
      ...json(["dependencies", clientFilesCourseDeps, "*"], "clientFilesCourse"),
    },
    {
      id: `${files}.dynamicDependencies.clientFilesCourse`,
      range: "*", files, rule: "client-files-course-exist", target: "file",
      ...json(["dynamicDependencies", "clientFilesCourseScripts", "*"], "clientFilesCourse"),
    },
  ] as const),

  // ── Assessments ──
  {
    id: "assessment.question",
    range: "*", files: courseFiles.assessment, rule: "question-exists", target: "question",
    ...json(["zones", "*", "questions", "*", "id"], "questions"),
  },
  {
    id: "assessment.alternative",
    range: "*", files: courseFiles.assessment, rule: "question-exists", target: "question",
    ...json(["zones", "*", "questions", "*", "alternatives", "*", "id"], "questions"),
  },

  // ── Elements in question.html (semantics from PL's element sources) ──
  {
    id: "pl-figure", range: "*", files: questionHtml, rule: "pl-figure-file-exist", target: "file",
    ...html({ tag: "pl-figure", attr: "file-name", directory: clientFilesDirectory, staticOnly: true }),
  },
  {
    id: "pl-file-download", range: "*", files: questionHtml, rule: "pl-file-download-file-exist", target: "file",
    ...html({ tag: "pl-file-download", attr: "file-name", directory: clientFilesDirectory, staticOnly: true }),
  },
  {
    id: "pl-code", range: "*", files: questionHtml, rule: "pl-code-file-exist", target: "fileOrDir",
    ...html({ tag: "pl-code", attr: "source-file-name", directory: sourceFileDirectory }),
  },
  {
    id: "pl-file-editor", range: "*", files: questionHtml, rule: "pl-file-editor-file-exist", target: "file",
    ...html({ tag: "pl-file-editor", attr: "source-file-name", directory: sourceFileDirectory }),
  },
  {
    id: "pl-graph", range: "*", files: questionHtml, rule: "pl-graph-file-exist", target: "file",
    ...html({ tag: "pl-graph", attr: "source-file-name", directory: sourceFileDirectory }),
  },
  {
    id: "pl-rich-text-editor", range: "*", files: questionHtml, rule: "pl-rich-text-editor-file-exist", target: "file",
    ...html({ tag: "pl-rich-text-editor", attr: "source-file-name", directory: sourceFileDirectory }),
  },
  {
    id: "pl-excalidraw", range: "*", files: questionHtml, rule: "pl-excalidraw-file-exist", target: "file",
    ...html({
      tag: "pl-excalidraw",
      attr: "source-file-name",
      directory: {
        default: ".",
        named: {
          ".": "fileDir",
          clientFilesQuestion: "clientFilesQuestion",
          clientFilesCourse: "clientFilesCourse",
          serverFilesCourse: "serverFilesCourse",
        },
      },
    }),
  },
  {
    id: "pl-xss-safe", range: "*", files: questionHtml, rule: "pl-xss-safe-file-exist", target: "fileOrDir",
    ...html({ tag: "pl-xss-safe", attr: "source-file-name", base: "fileDir" }),
  },
  {
    id: "pl-template", range: "*", files: questionHtml, rule: "pl-template-file-exist", target: "file",
    ...html({
      tag: "pl-template",
      attr: "file-name",
      directory: {
        default: "serverFilesCourse",
        named: {
          question: "fileDir",
          clientFilesQuestion: "clientFilesQuestion",
          clientFilesCourse: "clientFilesCourse",
          serverFilesCourse: "serverFilesCourse",
          courseExtensions: "courseExtensions",
        },
      },
    }),
  },
] as const satisfies readonly RefSpec[];

/** Ids of the existence rules generated from `refSpecs`. */
export type RefRuleId = (typeof refSpecs)[number]["rule"];
